/** Single source of truth for the vocabulary shared by the API and the UI. */

export const PROMISE_STATUS = {
  DRAFT: 'DRAFT',
  FUNDED: 'FUNDED',
  ACTIVE: 'ACTIVE',
  PARTIALLY_VERIFIED: 'PARTIALLY_VERIFIED',
  READY_TO_FULFILL: 'READY_TO_FULFILL',
  FULFILLED: 'FULFILLED',
  CONTESTED: 'CONTESTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
};

/** Statuses the backend will never move away from on its own. */
export const TERMINAL_PROMISE_STATUS = [
  PROMISE_STATUS.FULFILLED,
  PROMISE_STATUS.CANCELLED,
];

export const CONDITION_STATUS = {
  PENDING: 'PENDING',
  AWAITING_PROOF: 'AWAITING_PROOF',
  VERIFYING: 'VERIFYING',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  CONTESTED: 'CONTESTED',
  WAIVED: 'WAIVED',
};

export const CONDITION_TYPE = {
  DELIVERABLE: 'deliverable',
  APPROVAL: 'approval',
  TEST: 'test',
  MILESTONE: 'milestone',
  QUALITY: 'quality',
  TIMELINE: 'timeline',
  CUSTOM: 'custom',
};

export const VERIFICATION_METHOD = {
  AI_ASSESSMENT: 'ai_assessment',
  DOCUMENT_REVIEW: 'document_review',
  URL_CHECK: 'url_check',
  TEST_REPORT: 'test_report',
  PARTICIPANT_CONFIRMATION: 'participant_confirmation',
  MANUAL_APPROVAL: 'manual_approval',
};

export const EVIDENCE_TYPE = {
  IMAGE: 'image',
  PDF: 'pdf',
  DOCUMENT: 'document',
  SCREENSHOT: 'screenshot',
  URL: 'url',
  INVOICE: 'invoice',
  REPOSITORY: 'repository',
  TEST_REPORT: 'test_report',
  DELIVERY_CONFIRMATION: 'delivery_confirmation',
  NOTE: 'note',
};

export const EVIDENCE_STATUS = {
  SUBMITTED: 'SUBMITTED',
  VERIFYING: 'VERIFYING',
  ACCEPTED: 'ACCEPTED',
  INSUFFICIENT: 'INSUFFICIENT',
  CONTRADICTED: 'CONTRADICTED',
  REJECTED: 'REJECTED',
};

export const VERDICT = {
  SUPPORTS: 'SUPPORTS',
  INSUFFICIENT: 'INSUFFICIENT',
  CONTRADICTS: 'CONTRADICTS',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  FUNDED: 'FUNDED',
  HELD: 'HELD',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
};

/**
 * A payout is asynchronous and can still fail after a release has been
 * authorised, so its state is tracked separately from PAYMENT_STATUS. These are
 * the states RazorpayX reports, plus NOT_SENT for a release that never reached
 * a provider (demo mode, or no destination on file).
 */
export const PAYOUT_STATUS = {
  NOT_SENT: 'NOT_SENT',
  QUEUED: 'queued',
  PENDING: 'pending',
  PROCESSING: 'processing',
  PROCESSED: 'processed',
  REVERSED: 'reversed',
  CANCELLED: 'cancelled',
  REJECTED: 'rejected',
  FAILED: 'failed',
};

/** States from which a payout will never move again. */
export const TERMINAL_PAYOUT_STATUS = [
  PAYOUT_STATUS.PROCESSED,
  PAYOUT_STATUS.REVERSED,
  PAYOUT_STATUS.CANCELLED,
  PAYOUT_STATUS.REJECTED,
  PAYOUT_STATUS.FAILED,
];

export const DISPUTE_STATUS = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  WITHDRAWN: 'WITHDRAWN',
};

export const AUDIT_ACTION = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  GOOGLE_IDENTITY_LINKED: 'GOOGLE_IDENTITY_LINKED',
  PROMISE_CREATED: 'PROMISE_CREATED',
  PROMISE_MODIFIED: 'PROMISE_MODIFIED',
  PROMISE_FUNDED: 'PROMISE_FUNDED',
  PROMISE_CANCELLED: 'PROMISE_CANCELLED',
  PROMISE_CONTESTED: 'PROMISE_CONTESTED',
  PROMISE_FULFILLED: 'PROMISE_FULFILLED',
  PROMISE_STATUS_CHANGED: 'PROMISE_STATUS_CHANGED',
  CONDITION_CREATED: 'CONDITION_CREATED',
  CONDITION_MODIFIED: 'CONDITION_MODIFIED',
  CONDITION_VERIFIED: 'CONDITION_VERIFIED',
  CONDITION_FAILED: 'CONDITION_FAILED',
  CONDITION_REMOVED: 'CONDITION_REMOVED',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  EVIDENCE_VERIFIED: 'EVIDENCE_VERIFIED',
  PROOF_ENGINE_ANALYSIS: 'PROOF_ENGINE_ANALYSIS',
  PAYMENT_RELEASED: 'PAYMENT_RELEASED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  DISPUTE_OPENED: 'DISPUTE_OPENED',
  DISPUTE_EVIDENCE_ADDED: 'DISPUTE_EVIDENCE_ADDED',
  DISPUTE_ANALYSED: 'DISPUTE_ANALYSED',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
};

export const NOTIFICATION_TYPE = {
  PROMISE_CREATED: 'PROMISE_CREATED',
  PROMISE_FUNDED: 'PROMISE_FUNDED',
  PROOF_RECEIVED: 'PROOF_RECEIVED',
  CONDITION_VERIFIED: 'CONDITION_VERIFIED',
  EVIDENCE_CONFLICT: 'EVIDENCE_CONFLICT',
  HEALTH_CHANGED: 'HEALTH_CHANGED',
  READY_FOR_FULFILLMENT: 'READY_FOR_FULFILLMENT',
  PAYMENT_FULFILLED: 'PAYMENT_FULFILLED',
  PROMISE_CONTESTED: 'PROMISE_CONTESTED',
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
};

export const CURRENCIES = ['INR', 'USD', 'EUR', 'GBP', 'AED', 'SGD'];
